on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
     - uses: actions/checkout@v1
     - uses: Azure/login@v1
       with:
         creds: ${{secrets.AZURE_CREDENTIALS}}
     - uses: azure/mysql@v1
       with:
        connection-string: ${{ secrets.CONNECTION_STRING }}
        server-name: demo-server1.mysql.database.azure.com
        sql-file: "sql/update_db.sql"
